From debian:latest As barista_cafe_img

RUN apt install -y httpd \
unzip \
wget

RUN wget https://www.tooplate.com/zip-templates/2137_barista_cafe.zip && unzip 2137_barista_cafe.zip
RUN rm -rf /var/www/html/* && mv -r 2137_barista_cafe /var/www/html/ 

ENTRYPOINT ["/usr/lib/httpd/bin/ctl"]
CMD ["-d", "FOREGROUND"]
